#!/usr/bin/env node

require('./utils/config.js');
rimraf = require('./utils/rimraf.js');

var fs = require('fs');
var verifyRequirements = require('./utils/verify-requirements');
var safeExec = require('./utils/child-process-wrapper.js').safeExec;
var path = require('path');
var pkg = require('../package.json');

// Executes an array of commands one by one.
function executeCommands(commands, done, index) {
  index = (index === undefined ? 0 : index);
  if (index < commands.length) {
    var command = commands[index];
    if (command.message)
      console.log(command.message);
    var options = null;
    if (typeof command !== 'string') {
      options = command.options;
      command = command.command;
    }
    safeExec(command, options, executeCommands.bind(this, commands, done, index + 1));
  }
  else
    done(null);
}

function copyFileSync(srcFile, destFile) {
  var BUF_LENGTH, buff, bytesRead, fdr, fdw, pos;
  BUF_LENGTH = 64 * 1024;
  buff = new Buffer(BUF_LENGTH);

  fdr = fs.openSync(srcFile, 'r');
  fdw = fs.openSync(destFile, 'w');
  bytesRead = 1;
  pos = 0;

  while (bytesRead > 0) {
    bytesRead = fs.readSync(fdr, buff, 0, BUF_LENGTH, pos);
    fs.writeSync(fdw, buff, 0, bytesRead);
    pos += bytesRead;
  }

  fs.closeSync(fdr);
  return fs.closeSync(fdw);
}

function bootstrap() {
  var npmPath = path.resolve(__dirname, '..', 'build', 'node_modules', '.bin', 'npm');
  var initialNpmCommand = fs.existsSync(npmPath) ? npmPath : 'npm';
  var npmFlags = ' --userconfig=' + path.resolve('.npmrc') + ' ';

  var buildInstallCommand = initialNpmCommand + npmFlags + 'install';
  var buildInstallOptions = {cwd: path.resolve(__dirname, '..', 'build')};
  var dedupeNpmCommand = npmPath + npmFlags + 'dedupe';

  if (process.argv.indexOf('--no-quiet') === -1) {
    buildInstallCommand  += ' --quiet';
    dedupeNpmCommand     += ' --quiet';
    buildInstallOptions.ignoreStdout = true;
  }

  var commands = [
    {
      command: buildInstallCommand,
      message: 'Installing build modules...',
      options: buildInstallOptions
    },
    {
      command: npmPath + ' ' + 'install',
      message: 'Installing modules...',
      options: {}
    },
  ];

  var tmpDir = process.env.TMPDIR || process.env.TEMP || '/tmp';
  var buildDir = path.join(tmpDir, pkg.name + '-build');

  if (fs.existsSync(buildDir) && !process.env.JENKINS_URL) {
    rimraf.sync(buildDir);
  }

  process.chdir(path.dirname(__dirname));
  executeCommands(commands, process.exit);
}

verifyRequirements(function(error, successMessage) {
  if (error) {
    console.log(error);
    process.exit(1);
  }

  console.log(successMessage);
  bootstrap();
});
